### ISSUE TITLE
Not working in Python 3.4.3

### ISSUE THREAD

**Issue by cfmitrah** [ezyang/git-ftp#82]
Not working in Python 3.4.3

**Comment by MatteoGheza** [comment]
You need to edit the file with 2to3 python tool

**Comment by MatteoGheza** [comment]
See the file:
[git-ftp_converted.txt](https://github.com/ezyang/git-ftp/files/3515120/git-ftp_converted.txt)

**Comment by MatteoGheza** [comment]
or view [this pr](https://github.com/ezyang/git-ftp/pull/87) by [mousavian](https://github.com/mousavian)
