### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by funprogrammer89** [ezyang/git-ftp#91]
I am just curious as I see 4 pull requests, some as old as 2016.

**Comment by ezyang** [comment]
Not really haha

**Comment by funprogrammer89** [comment]
Don't have the time?

**Comment by ezyang** [comment]
Not using it lol

**Comment by funprogrammer89** [comment]
Haha, that makes sense. I have not used it but I wrote a more basic version of this software, [Git-FTP-Py](https://github.com/funprogrammer89/Git-FTP-Py) before finding this software but haven't tested it extensively yet. I was using [Git FTP](https://github.com/git-ftp/git-ftp) but was having issues with filenames with spaces not being uploaded and not even making me aware the files weren't uploading and various other things. Is this software fairly robust?

**Comment by ezyang** [comment]
Judging from the number of open issues, I guess not!
